<?php 
$data = '<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
<url><loc>https://www.indiamacroadvisors.com/</loc></url>
<url><loc>https://www.indiamacroadvisors.com/aboutus/</loc></url>
<url><loc>https://www.indiamacroadvisors.com/products/</loc></url>
<url><loc>https://www.indiamacroadvisors.com/aboutus/career/</loc></url>
<url><loc>https://www.indiamacroadvisors.com/contact/</loc></url>
<url><loc>https://www.indiamacroadvisors.com/products/offerings/</loc></url>
<url><loc>https://www.indiamacroadvisors.com/page/category/economic-indicators/gdp-business-activity/gdp/</loc></url>
<url><loc>https://www.indiamacroadvisors.com/page/category/economic-indicators/gdp-business-activity/index-of-industrial-production/</loc></url>
<url><loc>https://www.indiamacroadvisors.com/page/category/economic-indicators/gdp-business-activity/8-core-industries/</loc></url>
<url><loc>https://www.indiamacroadvisors.com/page/category/economic-indicators/international-balance/balance-of-payment-bop/</loc></url>
<url><loc>https://www.indiamacroadvisors.com/page/category/economic-indicators/international-balance/balance-of-trade/</loc></url>
<url><loc>https://www.indiamacroadvisors.com/page/category/economic-indicators/international-balance/export-by-commodities/</loc></url>
<url><loc>https://www.indiamacroadvisors.com/page/category/economic-indicators/international-balance/external-debt/</loc></url>
<url><loc>https://www.indiamacroadvisors.com/page/category/economic-indicators/international-balance/foreign-investment/</loc></url>
<url><loc>https://www.indiamacroadvisors.com/page/category/economic-indicators/leading-indicators-/consumer-confidence-survey/</loc></url>
<url><loc>https://www.indiamacroadvisors.com/page/category/economic-indicators/leading-indicators-/survey-of-professional-forecasters/</loc></url>
<url><loc>https://www.indiamacroadvisors.com/page/category/economic-indicators/inflation-prices/consumer-price-index/</loc></url>
<url><loc>https://www.indiamacroadvisors.com/page/category/economic-indicators/inflation-prices/wholesale-price-index/</loc></url>
<url><loc>https://www.indiamacroadvisors.com/page/category/economic-indicators/inflation-prices/consumer-price-index-states/</loc></url>
<url><loc>https://www.indiamacroadvisors.com/page/category/economic-indicators/inflation-prices/house-price/</loc></url>
<url><loc>https://www.indiamacroadvisors.com/page/category/economic-indicators/money-and-banking/bank-credit-nonfood/</loc></url>
<url><loc>https://www.indiamacroadvisors.com/page/category/economic-indicators/money-and-banking/money-supply/</loc></url>
<url><loc>https://www.indiamacroadvisors.com/page/category/economic-indicators/money-and-banking/payment-system-indicators/</loc></url>
<url><loc>https://www.indiamacroadvisors.com/page/category/economic-indicators/government-accounts/</loc></url>
<url><loc>https://www.indiamacroadvisors.com/page/category/economic-indicators/financial-markets/exchange-rate/</loc></url>
<url><loc>https://www.indiamacroadvisors.com/page/category/economic-indicators/financial-markets/foreign-exchange-reserves/</loc></url>
<url><loc>https://www.indiamacroadvisors.com/page/category/economic-indicators/labor-market/population/</loc></url>
<url><loc>https://www.indiamacroadvisors.com/page/category/economic-indicators/labor-market/indian-population-by-states/</loc></url>
<url><loc>https://www.indiamacroadvisors.com/page/category/economic-indicators/labor-market/unemployment-rate/</loc></url>
<url><loc>https://www.indiamacroadvisors.com/page/category/reserve-bank-of-india/rbi-policy-review/</loc></url>
<url><loc>https://www.indiamacroadvisors.com/page/category/reserve-bank-of-india/rbi-balance-sheet/</loc></url>
<url><loc>https://www.indiamacroadvisors.com/page/category/premium-data/fridge-ownership-by-states/</loc></url>
<url><loc>https://www.indiamacroadvisors.com/page/category/premium-data/rural-fridge-ownership-by-states/</loc></url>
<url><loc>https://www.indiamacroadvisors.com/page/category/premium-data/world-economy/long-term-economic-trend/</loc></url>
<url><loc>https://www.indiamacroadvisors.com/page/category/economic-indicators/international-balance/balance-of-trade/</loc></url>
<url><loc>https://www.indiamacroadvisors.com/page/category/economic-indicators/money-and-banking/money-supply/</loc></url>
<url><loc>https://www.indiamacroadvisors.com/page/category/economic-indicators/financial-markets/exchange-rate/</loc></url>
<url><loc>https://www.indiamacroadvisors.com/page/category/economic-indicators/inflation-prices/wholesale-price-index/</loc></url>
<url><loc>https://www.indiamacroadvisors.com/page/category/economic-indicators/labor-market/unemployment-rate/</loc></url>
<url><loc>https://www.indiamacroadvisors.com/seminar/</loc></url>
<url><loc>https://www.indiamacroadvisors.com/aboutus/termsofuse/</loc></url>
<url><loc>https://www.indiamacroadvisors.com/aboutus/privacypolicy/</loc></url>
<url><loc>https://www.indiamacroadvisors.com/reports/view/reports/estimating-the-economic-impact-of-cattle-slaughter-ban/</loc></url>
</urlset>';
echo $data;
?>