/bin/cp backup/controller/reports_controller.php /var/www/www/controller/reports_controller.php
/bin/cp backup/controller/user_controller.php /var/www/www/controller/user_controller.php
/bin/cp backup/admin/listseopages.php /var/www/www/admin/listseopages.php
/bin/cp backup/admin/category_ajax.php /var/www/www/admin/category_ajax.php
/bin/cp backup/admin/deleteseopage.php /var/www/www/admin/deleteseopage.php
/bin/cp backup/admin/addseopage.php /var/www/www/admin/addseopage.php
/bin/cp backup/admin/lib/class.category.php /var/www/www/admin/lib/class.category.php
/bin/cp backup/admin/lib/class.post.php /var/www/www/admin/lib/class.post.php
/bin/cp backup/admin/lib/class.seopages.php /var/www/www/admin/lib/class.seopages.php
/bin/cp backup/admin/editUser.php /var/www/www/admin/editUser.php
/bin/cp backup/admin/controlPanel.php /var/www/www/admin/controlPanel.php
/bin/cp backup/admin/js/jma_admin.js /var/www/www/admin/js/jma_admin.js
/bin/cp backup/admin/header.php /var/www/www/admin/header.php
/bin/cp backup/admin/editseopage.php /var/www/www/admin/editseopage.php
/bin/cp backup/css/master.css /var/www/www/css/master.css
/bin/cp backup/modal/user_modal.php /var/www/www/modal/user_modal.php
/bin/cp backup/modal/seopages_modal.php /var/www/www/modal/seopages_modal.php
/bin/cp backup/alanee_classes/common/alaneecommon_class.php /var/www/www/alanee_classes/common/alaneecommon_class.php
/bin/cp backup/alanee_classes/payment/paypal_class.php /var/www/www/alanee_classes/payment/paypal_class.php
/bin/cp backup/images/btn/activate_account_btn.png /var/www/www/images/btn/activate_account_btn.png
/bin/cp backup/view/user/myaccount_user_trial.php /var/www/www/view/user/myaccount_user_trial.php
/bin/cp backup/view/user/signin_confirm.php /var/www/www/view/user/signin_confirm.php
/bin/cp backup/view/user/signup.php /var/www/www/view/user/signup.php
/bin/cp backup/view/user/signin_success.php /var/www/www/view/user/signin_success.php
/bin/cp backup/view/templates/default.php /var/www/www/view/templates/default.php
/bin/cp backup/js/menu.js /var/www/www/js/menu.js